server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratings
    username: root
    password: bruno
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
  instance:
    prefer-ip-address: true
